### ISSUE TITLE
Chinese characters become garbled after signing.

### ISSUE THREAD

**Issue by cg1132001** [bertjohnson/OpaqueMail#22]
I tried to use MailMessage class to create a signed email.
This mail contains Chinese characters in the subject and body, and they become garbled after signing.
I set the values of SubjectEncoding and BodyEncoding, but they don't work and the characters are still garbled.
If I don't sign this mail, it doesn't happen.
How can I do to solve this problem?
Thanks.

**Comment by bertjohnson** [comment]
There have been encoding improvements in OpaqueMail and no recent reports, so closing this issue. If you run into problems, please open a new issue and include some example text for testing. Thanks.
