### ISSUE TITLE
Getting 503 5.5.2 'Send hello first' errors.... when using outlook.com smtp host

### ISSUE THREAD

**Issue by nicpot** [bertjohnson/OpaqueMail#35]
Hey Bert. Unless I'm missing something obvious, I cannot send your standard example email (as in your v2.2.0 tutorial) using outlook.com as smtp host. It works with using gmail.com as smtp host though. Is there something additional I need to set when using outlook.com?

**Comment by bertjohnson** [comment]
Thanks for the report, nicpot.  While we were sending an "EHLO" prior to TLS negotation, some servers (including outlook.com) required another "EHLO" after the TLS session is started.  That's consistent with RFC3207.

That change is now in place and ready to test with the OpaqueMail 2.2.3 release.

**Comment by nicpot** [comment]
Thanks Bert, will check it out!

One last thing tho, There are some missing files in the download zip: Pgp.cs in OpaqueMail proj and a couple of packages.config in some projects

Thanks again for the fix

Nic

**Comment by bertjohnson** [comment]
Thanks Nic!  I didn't realize those files were being excluded.  They should now be checked in.

**Comment by jstedfast** [comment]
Hey Bert,

Speaking of PGP, have you given any thought to use [MimeKit](https://github.com/jstedfast/MimeKit) for S/MIME and PGP instead of duplicating efforts? I would love it if we could work together.

**Comment by nicpot** [comment]
Thanks Bert. I have tested it now and all works as expected ☺

Nic
