### ISSUE TITLE
Cannot be used with strong-named assemblies

### ISSUE THREAD

**Issue by hurcane** [bertjohnson/OpaqueMail#39]
I was reviewing OpaqueMail to use in an existing project. The project happens to run in an environment (Component Services, a.k.a. COM+) that requires all assemblies, including any referenced assemblies, to have a strong name. The NuGet package does not include a strong-named DLL, so it cannot be used in this environment.

We will try building from source and using our own key, but it would be easier to use if the project included an assembly with a strong name.

**Comment by bertjohnson** [comment]
Thanks for the report, hurcane.  Good call.

Starting with version 2.2.4, this is signed as a strong-named DLL.  You should be able to download from https://www.nuget.org/packages/OpaqueMail/.
