### ISSUE TITLE
SecureString support?

### ISSUE THREAD

**Issue by beppe9000** [bertjohnson/OpaqueMail#46]
> Microsoft has implemented the SecureString class in an effort to provide better security with sensitive information (like credit cards, passwords, etc.).  It automatically provides:
> - encryption (in case of memory dumps or page caching) 
> - pinning in memory
> - ability to mark as read-only (to prevent any further modifications) 
> - safe construction by NOT allowing a constant string to be passed in

Could this be useful for password handling in OpaqueMail? Obviously the old constructors that accept a normal string should remain for compatibility.

**Comment by bertjohnson** [comment]
Hi beppe9000, thanks for the feedback.

SecureString is a great idea in theory, although it has limitations in practice. [Check out this StackOverflow thread](https://stackoverflow.com/questions/26190938/is-securestring-ever-practical-in-a-c-sharp-application), which explores the pros and cons.

In short, SecureString can lull developers into a false sense of security if they mistakenly convert SecureString to or from managed strings (since the raw password will be stored in memory). While that shouldn't ever happen, there's a lot of source code online that tells users how to do just that.

I'm open to adding a SecureString constructor. Please feel free to submit a pull request. Thanks!

**Comment by beppe9000** [comment]
body { font-family:'Times New Roman'; font-size:13px}

Very wise words indeed.In data 25 novembre 2016 alle ore 07:04:25, Bert Johnson <notifications@github.com> ha scritto:Hi beppe9000, thanks for the feedback.
SecureString is a great idea in theory, although it has limitations in practice. Check out this StackOverflow thread, which explores the pros and cons.
In short, SecureString can lull developers into a false sense of security if they mistakenly convert SecureString to or from managed strings (since the raw password will be stored in memory). While that shouldn't ever happen, there's a lot of source code online that tells users how to do just that.
I'm open to adding a SecureString constructor. Please feel free to submit a pull request. Thanks!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bertjohnson/OpaqueMail","title":"bertjohnson/OpaqueMail","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bertjohnson/OpaqueMail"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bertjohnson in #46: Hi beppe9000, thanks for the feedback.\r\n\r\nSecureString is a great idea in theory, although it has limitations in practice. [Check out this StackOverflow thread](https://stackoverflow.com/questions/26190938/is-securestring-ever-practical-in-a-c-sharp-application), which explores the pros and cons.\r\n\r\nIn short, SecureString can lull developers into a false sense of security if they mistakenly convert SecureString to or from managed strings (since the raw password will be stored in memory). While that shouldn't ever happen, there's a lot of source code online that tells users how to do just that.\r\n\r\nI'm open to adding a SecureString constructor. Please feel free to submit a pull request. Thanks!"}],"action":{"name":"View Issue","url":"https://github.com/bertjohnson/OpaqueMail/issues/46#issuecomment-262886757"}}}

**Comment by bertjohnson** [comment]
Hi beppe9000, I went ahead and added support for `SecureString` in the constructors of `ImapClient` and `Pop3Client` as of release 2.4.0. `SmtpClient `can also utilize `SecureString` via the default `NetworkCredential` constructor. Thanks again for the suggestion.

**Comment by beppe9000** [comment]
Good to know! I will certainly make use of them next time I can.
