### ISSUE TITLE
Modify CertHelper FindBySerialNumber to FindByThumbprint

### ISSUE THREAD

**Issue by miketheitguy** [bertjohnson/OpaqueMail#54]
Thumbprints are more easily able to uniquely identify the certificate to use. I could have multiple certificates loaded with serial number collisions (they're only unique to the CA that issued them) or have duplicate subject names (it's useful to have multiple certs for different purposes for reasons like Key Escrow, etc.)

Thumbprint is a MUCH safer way to identify a certificate uniquely.

**Comment by bertjohnson** [comment]
Mike, great suggestion, thanks. I just added `GetCertificateByThumbprint()` to version 2.4.1.
