### ISSUE TITLE
Error on some retrievals

### ISSUE THREAD

**Issue by kalzon1** [bertjohnson/OpaqueMail#55]
Hello,  

This code has been create.  I really appreciate the work you've put into it.  Thanks :)

I found what seems to be an error/issue in the code.  I was getting an error message "Index and Length must refer to a location within the string."

After running several tests and stepping through the code I found the following:
OpaqueMail.ImapCLient.GetMessageParialHelper()
line 2391
response = response.Substring(lineBreak + 2, bodyLength);
this was trying to get a substring returned longer than the message.
In my case, pulling an email from gmail, 

- the linebreak was 36 (+2) so 38 
- response.Length = 6979
- bodylength returned 6954
So that equaled 6992 and returned an error.

So a possible alteration could be  (at least this is what I did, but I'd love to hear what you would do)

(OLD)
                if (bodyLength > 0)
                        response = response.Substring(lineBreak + 2, bodyLength);
                else
                {
                    response = response.Substring(response.IndexOf("\r\n") + 2);
                    response = response.Substring(0, response.Length - 2);
                }

(NEW)
                if (bodyLength > 0)
                    if (response.Length < bodyLength + lineBreak + 2)
                    {
                        response = response.Substring(lineBreak + 2);
                    }
                    else
                    {
                        response = response.Substring(lineBreak + 2, bodyLength);
                    }
                else
                {
                    response = response.Substring(response.IndexOf("\r\n") + 2);
                    response = response.Substring(0, response.Length - 2);
                }

**Comment by bertjohnson** [comment]
Thanks for the report, kalzon1. I'll look into it.

In the meantime, would you be able to forward an email that triggers that error? You can send to bert at opaquemail dot org.

Your workaround looks like it will work, but I'd like to trace exactly how the message is being processed in case the source of the issue is elsewhere.

**Comment by kalzon1** [comment]
I tested forwarding the email to myself and did not have the issue from the forward.

Interesting though... It was not just one email it was about 8 so far on a new gmail account.

I have also received emails from those same people on a gmail account I've had for years and those came through your tool without any problem.  So I wonder if it is some gmail setting, but I've looked at the ones I can configure and they are set the same.

I'll try emailing it to this email, but not sure it will work.  Is there another email address I can sent it to?

Keith Longwell

________________________________

**Comment by kalzon1** [comment]
---------- Forwarded message ----------
From: Heather Everson <heather.everson@zeemedrdg.com>
Date: Fri, Jan 6, 2017 at 2:20 PM
Subject: RE: Conference call summary
To: Sam Wandzilak <sam.wandzilak@keystonesoftware.com>, David Cerates <
david.cerates@zeemedrdg.com>, Walt Everson <walt.everson@zeemedrdg.com>
Cc: Cathy Weatherholtz <cathy.weatherholtz@zeemedrdg.com>, Amanda Gaus <
amanda.gaus@zeemedrdg.com>, Longwell <keith@cornerstonet.com>


Thank you for your help. I will alert our sales staff.





Heather Everson

Business Manager

WADDEE Inc. T/A Zee Medical Service Company

2745 B Leiscz’s Bridge Road

Reading PA 19605

610-926-1401 x 136 <(610)%20926-1401>

Fax: 610-926-0568 <(610)%20926-0568>







*From:* Sam Wandzilak [mailto:sam.wandzilak@keystonesoftware.com]
*Sent:* Friday, January 06, 2017 2:53 PM
*To:* David Cerates; Walt Everson; Heather Everson
*Cc:* Cathy Weatherholtz; Amanda Gaus; 'Longwell'
*Subject:* Conference call summary



Dave, Keith and myself just finished up our conference call to see why some
of the customer and item pricing between Sage and Trakker was different.



We discovered that some pricing records from Sage were not being
synchronized over to the SQL server and therefore not available for Trakker
to read and use on the handhelds/tablets.



I will log into the Sage server this evening around 8:00 pm and manually
re-synchronize all the Sage databases with the SQL server.  After that
Keith will pull all the records dated 7/1/2016 (just before our last system
upgrade) and synchronize that with the handhelds and tablets.



The salespersons should leave their handhelds and tablets logged into the
Trakker program over the weekend as there will be a large update to ensure
all the data is up-to-date.



If anyone has any questions please call or email me



Thanks,



Sam P Wandzilak

800.289.9109 x 112 <(800)%20289-9109>

610.685.2112 <(610)%20685-2112> fax

www.keystonesoftware.com

**Comment by bertjohnson** [comment]
Thanks for your help troubleshooting. For privacy, I deleted the email from this thread, but I received the copy you forwarded.

Like you, I didn't run into any problems from the forward. I also tried to recreate the problem using a few different email servers, but wasn't able to.

Your workaround looks good and I manually crafted problematic server responses to test it, which all succeeded, so I've incorporated that into OpaqueMail 2.4.2. Please download from GitHub and test again. Once we know everything works well, I'll update NuGet.

Thanks again.

**Comment by kalzon1** [comment]
Hello,


I downloaded and tested the update.  I put break points in for both response sizes.  Some of the emails come in and work on the old code, some on the new.


So looks good.


Thanks,

Keith


________________________________

**Comment by bertjohnson** [comment]
Great, thanks for confirming.
