### ISSUE TITLE
Very slow performance 

### ISSUE THREAD

**Issue by batooo** [bertjohnson/OpaqueMail#59]
Why sending directly to SMTP (mailgun) is like 2 secound but proxing via OpaqueMail to Mailgun is like 15 seconds.

My config:
[http://prntscr.com/ek1njm](http://prntscr.com/ek1njm)

Here is one log where timespan is 30 secounds to forward.
`[3/14/2017 11:13:50 PM]	310f182d-7537-48df-ae78-d4f757b4ca92	2	VERBOSE	Forwarding message from {xxxx} with subject {WP Mail SMTP: Test mail to xxxxx@yahoo.com} and size of {423}.
[3/14/2017 11:14:20 PM]	310f182d-7537-48df-ae78-d4f757b4ca92	2	RAW	C: Date: Tue, 14 Mar 2017 23:13:50 +0000`

Also when i restart the service i`m always getting error:

`CRITICAL	Exception when starting proxy: A blocking operation was interrupted by a call to WSACancelBlockingCall`

Then i need to do like STOP -> WAIT -> START the service.

Any suggestion?

**Comment by batooo** [comment]
Looking at source code, looks like you try to generate certificate even <SMIMESign>False</SMIMESign>

**Comment by batooo** [comment]
ElapsedMilliseconds: 29502

`
  var watch = System.Diagnostics.Stopwatch.StartNew();
                                                // Look up the S/MIME signing certificate for the current sender.  If it doesn't exist, create one.
                                                message.SmimeSigningCertificate =
                                                    CertHelper.GetCertificateBySubjectName(StoreLocation.LocalMachine,
                                                        message.From.Address);
                                                if (message.SmimeSigningCertificate == null)
                                                    message.SmimeSigningCertificate =
                                                        CertHelper.CreateSelfSignedCertificate(
                                                            "E=" + message.From.Address, message.From.Address,
                                                            StoreLocation.LocalMachine, true, 4096, 10);

                                                watch.Stop();
                                                var elapsedMs = watch.ElapsedMilliseconds;
`

**Comment by bertjohnson** [comment]
Hi batooo, thanks for the report and for digging into the performance. You're right that the proxy was unnecessarily generating certificates even when S/MIME signing was disabled. That's now fixed in version 2.5.1, which should speed things up.

Regarding other factors of slow performance, I'm sure the proxy could be optimized significantly. Pull requests are welcome. Thanks.

**Comment by bertjohnson** [comment]
Closing this since there are no specific bottlenecks identified. Feel free to reopen or submit pull requests. Thanks.
