### ISSUE TITLE
Boundary with a capital B is not supported

### ISSUE THREAD

**Issue by kalzon1** [bertjohnson/OpaqueMail#65]
I have had a few emails coming in with attachments that have had issues and cause the OpaqueMail to not handle the exception.

One I found is in MailMessage.cs around line 424 looking at "content-type" 
MimeBoundaryName = Function.ExtractMimeParameter(ContentType, "boundary")

if instead inside is Boundary it throws an unhandled exception.

So you might alter the 
Functions.ExtractMimeParameter(...)
from
            int parameterPos = mimeHeader.IndexOf(mimeParameter);
to
            int parameterPos = mimeHeader.ToLower().IndexOf(mimeParameter.ToLower());

This fixed this issue for me.
Thanks again for all your efforts on this project.

**Comment by bertjohnson** [comment]
Thanks for this report, kalzon1. This should be fixed with release 2.5.4.

The method `ExtractMimeParameter()` in Functions.cs now matches using `StringComparison.OrdinalIgnoreCase`. Thanks.
