### ISSUE TITLE
subject line with the word FUILD will not download

### ISSUE THREAD

**Issue by kalzon1** [bertjohnson/OpaqueMail#67]
Your probably tired of hearing from me, but I've found another minor code update.

Had an email that would not come through, as it turns out it is because the word FLUID was in the subject line so ImapClient.GetMessagePartialHelper would not get the uid.

Altered:
                if (!int.TryParse(Functions.ReturnBetween(response, "UID ", " "), out uid))
                    int.TryParse(Functions.ReturnBetween(response, "UID ", ")"), out uid));

to
                if (!int.TryParse(Functions.ReturnBetween(response, "UID ", " "), out uid))
                {
                    if (!int.TryParse(Functions.ReturnBetween(response, "UID ", ")"), out uid))
                    {
                        //To allow for a subject line with the word FLUID in it
                        int.TryParse(Functions.ReturnBetween(response, " UID ", ")"), out uid);
                    }
                }

(Still would not handle if the subject had UID in it for Universal Identifier)

**Comment by bertjohnson** [comment]
Thanks for all of the detailed reports, kalzon1! I appreciate everything you're sharing.

This is fixed in release 2.5.4. That's an embarrassing mistake - the "UID" matching was far too greedy before. Please test again.
